### ISSUE TITLE
Add navigation menu between lessons

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#101]

**Comment by winter-yuki** [comment]
@zuevval how many lessons will we have at all? Approximately.

**Comment by winter-yuki** [comment]
The number does not matter I think. Scroll list should help

**Comment by zuevval** [comment]
> @zuevval how many lessons will we have at all? Approximately.

about 15-20 lessons on letters and digits. Of course, even basic course will be incomplete without special symbols; I suppose, about 25 lessons in total

**Comment by winter-yuki** [comment]
Okay, thank you. Is there a logical possibility to split this amount of lessons to three\four courses for example to simplify navigation.

**Comment by zuevval** [comment]
> Okay, thank you. Is there a logical possibility to split this amount of lessons to three\four courses for example to simplify navigation.

I will ponder it. I doubt that it may not simplify navigation, moreover, it might do just the opposite
