### ISSUE TITLE
Improve step text formatting in DSL

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#102]
HTML with come preprocessing maybe

**Comment by zuevval** [comment]
what's wrong with current formatting?

**Comment by winter-yuki** [comment]
> what's wrong with current formatting?

It is needed to add `|` at the beginning of each line. I want to make it possible to write simply in html. Without issues with new lines.

**Comment by zuevval** [comment]
Since that's I who is supposed to fill lessons, I want to ensure you that I do not care

**Comment by winter-yuki** [comment]
It does not. Every time you add a new line in code, new line appears on the step view. And many other issues.

**Comment by zuevval** [comment]
ok, finally I've understood the importance of this task
