### ISSUE TITLE
Add types of steps and possibility to disable them it settings

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#104]
For example, steps where you should have book

**Comment by winter-yuki** [comment]
@zuevval what such specific types of steps will we have?

**Comment by zuevval** [comment]
https://trello.com/c/JHF7nS8x/153-%D0%B2%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%BF%D1%83%D0%BD%D0%BA%D1%82-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82

**Comment by zuevval** [comment]
> @zuevval what such specific types of steps will we have?

- steps with reference to book

that's all for this semester

**Comment by winter-yuki** [comment]
Okay, thank you
