### ISSUE TITLE
Arch of multiplatform apps on Kotlin

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#114]
Investigate multiplatform apps arch and write guidelines to build arch of this app. To be able to maybe publish it for other platforms in the future.

**Comment by zuevval** [comment]
totally blind would appreciate Nokia C5 (seriously)

**Comment by winter-yuki** [comment]
Oh, I've meant IOS. But if the LLVM backend supports the Nokia C5 processor arch, it can be possible.

**Comment by winter-yuki** [comment]
But, no Nokia I guess :(

**Comment by winter-yuki** [comment]
To be multiplatform, our app should not use a room database, which is a very suitable one. If we'll decide to go to the App Store, we will make such refactoring.

**Comment by winter-yuki** [comment]
But in this task, I want to separate room-specific things from other code and maybe to extract common module of our app.

**Comment by zuevval** [comment]
don't you want to postpone it for a while? Maybe  solve #78 first?

**Comment by winter-yuki** [comment]
> don't you want to postpone it for a while? Maybe solve #78 first?

I don't know what to do with it :)

**Comment by zuevval** [comment]
> > don't you want to postpone it for a while? Maybe solve #78 first?
> 
> I don't know what to do with it :)

Set visibility to *invisible* by default. Or something alike, I really do not care much about implementation. What I care about is that current state of things is worse than the one I implemented with stubbed views.
