### ISSUE TITLE
Title on steps

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#132]
What types of steps do really need titles?

**Comment by winter-yuki** [comment]
@zuevval

**Comment by zuevval** [comment]
Maybe none

**Comment by zuevval** [comment]
But user should know where he is, e. g. suppose he's studying with a teacher and teacher says "navigate to lesson 2 step 3". Is in possible to append an index to the title in the upmost bar? e. g. "1.1 Informational step", "1.3 Symbol input"

Also we shouldn't remove "title" property from steps (just in case)

**Comment by winter-yuki** [comment]
I want to remove the title from the `step` entity to enhance customization potential. We can add title to particular step types if it is needed there hand-written. On the other steps, it could be generated in some way.

Great insight! I think it could be done by adding a two-value primary key to the steps: `lessons_id`, `step_id`, so step count from the very beginning of the lesson will be just its number. It could be done a bit later.

**Comment by winter-yuki** [comment]
#135 added corresponding ticket

**Comment by zuevval** [comment]
> I want to remove the title from the `step` entity to enhance customization potential. We can add title to particular step types if it is needed there hand-written. On the other steps, it could be generated in some way.

Ok, for now I will add a title as a part of text in every first step of every lesson

**Comment by winter-yuki** [comment]
Great! So, this issue can be closed, I think
