### ISSUE TITLE
Fix too big toast duration

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#214]
When user presses "hint" seven times, the toast remains seven times longer on the screen.

This may be inconvenient for sighted.

This and similar issues with toast duration should be solved. At least we should write a wrapper for Toast that will prevent **the same** toast from being showed multiple times.

See https://stackoverflow.com/questions/10070108/can-i-cancel-previous-toast-when-i-want-to-show-an-other-toast

**Comment by winter-yuki** [comment]
All possible solutions ([1](https://stackoverflow.com/questions/10070108/can-i-cancel-previous-toast-when-i-want-to-show-an-other-toast), [2](https://stackoverflow.com/questions/2755277/android-hide-all-shown-toast-messages), [3](https://stackoverflow.com/questions/4395062/how-to-cancel-toast)) make code much more complicated, it's not worth it.

**Comment by winter-yuki** [comment]
This issue should de closed, I guess

**Comment by zuevval** [comment]
I want to try it myself

**Comment by winter-yuki** [comment]
There is no way for me to approve such changes.

**Comment by winter-yuki** [comment]
No information about how different talkback versions work with possible solutions. It task doesn't worth any code pollution

**Comment by zuevval** [comment]
don't worry. I'm not going to change more than 10 lines of code and certainly I'm not going to railroad these changes. If you disapprove it, then OK, I will just give up.
