### ISSUE TITLE
Investigate 2-star feedback and correct mistakes if any

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#221]
https://play.google.com/store/apps/details?id=com.github.braillesystems.learnbraille&hl=ru&reviewId=gp%3AAOqpTOHeM0yRzRscXNKSG1m3HQ61IsXXN_dmDLouZ6zlGhgKK0ithZAIZPW_SY1_IOoUPmNNATUOgoIYLHO4Rw

>В приложении много ошибок. Буква "Ю" точки 1,2,5,6. Буква "Э" точки 2,4,6. В объяснении буквы "Т" много ошибок. Точки 2,4,5 - буква "Ж", а не "Х". В описании знака препинания "точка" всё верно, но при попытке написать, заставляет писать восклицательный знак (точки 2,3,5), а не литературную точку (точки 2,5,6). Не хватает самых часто используемых знаков препинания. Надо обговорить момент насчёт письма, т.к. на брайлевском приборе написание происходит в зеркальном отражении справа налево.

**Comment by winter-yuki** [comment]
What is 'mirror typing'?

**Comment by zuevval** [comment]
> What is 'mirror typing'?

When you write in Braille using [slate and stylus](https://en.wikipedia.org/wiki/Slate_and_stylus), dots 1, 2, 3 are on the right and dots 4, 5, 6 are on the left. Reversed mode is implemented in the [Braille Buddy Android app](https://play.google.com/store/apps/details?id=org.sugamya.braille&hl=ru), other apps do not comprise it as far as I know, but I remember that Alexey Viktorovich proposed a similar idea.

**Comment by winter-yuki** [comment]
> > What is 'mirror typing'?
> 
> When you write in Braille using [slate and stylus](https://en.wikipedia.org/wiki/Slate_and_stylus), dots 1, 2, 3 are on the right and dots 4, 5, 6 are on the left. A mode with interchanged columns is implemented in the [Braille Buddy Android app](https://play.google.com/store/apps/details?id=org.sugamya.braille&hl=ru), other apps do not comprise it as far as I know, but I remember that Alexey Viktorovich proposed a similar idea.

Created another issue for this

**Comment by zuevval** [comment]
Ok, and I created an issue #224 about “too few punctuation symbols”, just for completeness
