### ISSUE TITLE
Extend course

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#224]
Add punctation and math symbols that are not in the Golubina course but are essential

Not another course, just a few additional lessons to this one

This continues #221

**Comment by zuevval** [comment]
Now it seems wise to solve this in two big steps:
- [ ] change current course as in [article](https://github.com/braille-systems/learn-braille/wiki/2020-august-roadmap) (see also docx from VN)
- [ ] add new steps based on Golubina

**Comment by winter-yuki** [comment]
I'll finish #185, so do not edit lesson numbers manually, it will be access like `||ilesson||` from lesson's text. If you need something else like this, just write about it here: #185.

**Comment by zuevval** [comment]
> I'll finish #185, so do not edit lesson numbers manually, it will be access like `||ilesson||` from lesson's text.

OK, it will be convenient, thank you. 

>  If you need something else like this, just write about it here: #185.

Nothing else has come in my mind so far.
