### ISSUE TITLE
introduce Greek and Latin symbols

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#241]
see [article](https://github.com/braille-systems/learn-braille/wiki/2020-august-roadmap), point 11

- [x] add caption on top of each symbol in Practice and in Materials Browser
- [x] add deck with Greek symbols
- [x] add deck with Latin symbols

**Comment by winter-yuki** [comment]
Maybe do not add new symbols to deck `All decks`?

**Comment by zuevval** [comment]
Then it must be renamed. Or include a variable part. Or something. I will think about it.

**Comment by zuevval** [comment]
> Maybe do not add new symbols to deck `All decks`?

@winter-yuki I have anticipated this problem, that's why I wanted to convert list of decks into settings screens with ticked list. But of course this all is still a subject to careful consideration.

**Comment by winter-yuki** [comment]
Decks menu's purpose is to choose a particular theme to work with. This problem should be solved on the level above: checkboxes that form decks list itself and `All cards` deck at the same time. Enough solution for this issue should be not to include new cards in the `All cards` deck. Also, an issue for such checkboxes in settings should be created.
