### ISSUE TITLE
Text padding

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#264]
`ShowDotsFragment`, `CardFragment`

**Comment by zuevval** [comment]
@winter-yuki May you remind me please whether this issue persists and what is it about?

I think we may add a small margin around text in `fragment_lessons_show_dots.xml`:

<img width=400 src=https://user-images.githubusercontent.com/23435506/105879701-8d86d100-6013-11eb-86b6-a6a197be1d39.png>

But what should I do with `card_fragment`? It seems that everything's OK

<img width=400 src=https://user-images.githubusercontent.com/23435506/105879781-a2636480-6013-11eb-9899-053c243508fe.png>

**Comment by winter-yuki** [comment]
Yes, it is about such margins. On the card fragment margin for letter title may be useful.

**Comment by zuevval** [comment]
I suppose I've solved this (it was easy)
<img height=400 src=https://user-images.githubusercontent.com/23435506/105970536-86ef6c80-609a-11eb-91c9-b5146d20ae1f.png> <img height=400 src=https://user-images.githubusercontent.com/23435506/105970608-9cfd2d00-609a-11eb-9058-fb0611222717.png>

This seems to have little effect, e. g. the screen below looks identical to its current version in the `dev` branch

<img height=400 src=https://user-images.githubusercontent.com/23435506/105972669-ebabc680-609c-11eb-86fe-c3f43ab69931.png>
