### ISSUE TITLE
HTML tags in ShowSymbol

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#271]
in `dev` ShowSymbol steps containing `<br>` tag look like this:

![image](https://user-images.githubusercontent.com/23435506/94374096-95d90900-0112-11eb-8277-2409671c9c30.png)

This is the aftermath of the last refactoring.

Specifically, this happened after https://github.com/braille-systems/learn-braille/commit/40e454f3deed0f50fd782c33ca203701aa6a3241

TODO: fix

**Comment by winter-yuki** [comment]
Fixed
