### ISSUE TITLE
Put a number sign in front of each number or digit

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#305]
In lessons, some numbers and digits are not preceded by a number sign. This was done on purpose, but Viktoria Nikolaevna pointed out that we should put a number sign *always* before a number (otherwise students may get used to writing numbers without a number sign, she says).

In practice, numbers and digits are never preceded by a number sign.

So:

- [x] Put a number sign everywhere in theory
- [x] Ask V.N.: what to do with practice? It would be tedious to always write it before each digit. Maybe just leave it as is?

**Comment by winter-yuki** [comment]
Just add extension function to the `_DSL` file and use it everywhere in the course for numbers instead of `inputChars`:

```kotlin
fun StepsBuilder.inputNumber(number: Int) {
    +Input(content.markers.getValue(MarkerType.NumberSign))
    inputChars(number.toString())
}
```
