### ISSUE TITLE
Check Greek symbol map

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learn-braille#312]
When I added Greek characters from Golubina's book to [AngelinaReader](https://github.com/IlyaOvodov/AngelinaReader), a user [pointed out](https://github.com/IlyaOvodov/AngelinaReader/issues/45) that it is Soviet mathematical Greek Braille, not modern literary Greek Braille. Therefore, either the symbol map should be changed in our app, or this fact should be mentioned in the lessons and in the browser help.

**Comment by zuevval** [comment]
If we change the mapping to literary Greek, it's probably wise to add digraphs (see [here](https://other.oire.org/Braille/Greek.html))

**Comment by zuevval** [comment]
I asked VN and she said that, indeed, the Braille mapping may vary across different areas (i.e. there are at least 3 standards for contractions in UEB). But in our *introductory* course, we should leave Greek as in Golubina (and mention the existence of alternative mappings).

**Comment by winter-yuki** [comment]
This choice should be mentioned in the help of the course and practice, I guess.

**Comment by zuevval** [comment]
> This choice should be mentioned in the help of the course and practice, I guess.

Uhm, I'd rather add it in the browser help, but not in the course/practice help - they are already quite long
