### ISSUE TITLE
Back to current step button

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#52]
`Current` means last not passed. Do we need this one really?

**Comment by zuevval** [comment]
sorry, I miss the point entirely, what's this all about? Which button do you mean?

**Comment by winter-yuki** [comment]
We now imagine steps navigation like this:
- from the main menu go to the first not passed step
- in the each step, except for the last one, the user can go to the previous step and to the next. So he can go far behind his current position in the course. And the purpose is to introduce a button like "to the current day" in the calendar.

**Comment by zuevval** [comment]
We shall not divide steps into passed and not passed, let's just navigate to current step and reduce number of buttons. **The goal for now is to reproduce LITERALLY what we had in alpha branch, no more and no less**.

**Comment by winter-yuki** [comment]
We have "pass" logic already for a long time.  And without it, it is very easy to be lost in the number of lessons. So okay, no such button, but logic we have now is very good to my opinion.

**Comment by zuevval** [comment]
> We have "pass" logic already for a long time. And without it, it is very easy to be lost in the number of lessons. So okay, no such button, but logic we have now is very good to my opinion.

hmm, tracking progress seems to be a good motivation for students. I agree that we might use "pass" logic in a while. Recently I thought that maybe it would be sensible to add a roll-out sidebar (though this idea is still under consideration), maybe we will show progress inside it.
