### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#58]
- [x] static analysis
- [x] code style checks
- [x] generate KDoc
- [x] unit tests
- [x] tests on AVD
- [ ] ~~deploy developers version from master to google play~~ considered unnecessary

**Comment by winter-yuki** [comment]
Getting error
```
/usr/bin/env: ‘sh\r’: No such file or directory
```

**Comment by zuevval** [comment]
my guess is that there is an inconsistency in line endings in some script. Maybe in `gradlew`?

**Comment by zuevval** [comment]
Yeah 😎

**Comment by winter-yuki** [comment]
Strange thing
