### ISSUE TITLE
Logic of steps with input in lessons

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#67]
Choose the logic version and implement it.

**Comment by winter-yuki** [comment]
My proposal is:

In regular fragments:
- prev (left)
- next (right)
- to the last step in the progress (upper right)

For steps with input:
- prev (left)
- next (right)
- to the last step in the progress (upper right)
- check correctness (upper left)

On next: 
- If the step has been passed already, navigate to the next.
- otherwise - check the correctness and navigate to the next only of input is correct.

Check correctness button simply disapears on non-input steps

**Comment by zuevval** [comment]
cold you please draw a picture?

**Comment by zuevval** [comment]
As Python zen goes, 
> simple is better than complex

so I really fancy two-button scheme everywhere. Later we may add a roll-out sidebar with a bunch of useful features, such as: to change input method, to receive a hint, to navigate to another lesson. There we may place this button 'go to the last step in progress'.

**Comment by winter-yuki** [comment]
Will currently use proposed version. Maybe will change after feedback.
