### ISSUE TITLE
Replace long toasts with short

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#87]
To let talkback to spell them better.

**Comment by winter-yuki** [comment]
It does not matter for talkback, but we should unify toast duration all over the app

**Comment by zuevval** [comment]
let's make them short

**Comment by zuevval** [comment]
consider creating a ticket in Trello

**Comment by winter-yuki** [comment]
> let's make them short

Yes, I agree

**Comment by winter-yuki** [comment]
> consider creating a ticket in Trello

Ok, if well will not have enough there
