### ISSUE TITLE
"To current step button"

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#95]
- replace the map icon with a more suitable one
- add a description in help

**Comment by zuevval** [comment]
Please either give an idea of 'more suitable' icon or let me remove the first point from this issue. Nav button is quite OK to my mind, but maybe there are better ideas?

**Comment by winter-yuki** [comment]
Maybe doubled arrow. Like `next`, but repeated two times. We've discussed it with @kaustika.

**Comment by zuevval** [comment]
I would like to move it to sidebar

**Comment by winter-yuki** [comment]
Sidebar everywhere seems a bad idea. I've written it in telegram for example. At least it is not a silver bullet.
